alias ls='ls --color=auto'
alias l='ls --color=auto'
alias ll='ls -lAh'
alias lt='ls -ahltr'
alias ldot='ls -d .*'
alias dux='du -xh --max-depth=1'
alias dush='du -sh'
alias df='df -kTh'
alias p='pwd'
alias RAM='free -m'
alias ..='cd ../'
alias cd..='cd ../'
alias ...='cd ../../'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias dux='du -xh --max-depth=1'
