alias caddyedit='sudo nano /etc/caddy/Caddyfile'
alias caddytest='caddy validate --config /etc/caddy/Caddyfile'
alias caddyreload='sudo systemctl reload caddy'
alias caddyrestart='sudo systemctl restart caddy'
alias caddystatus='sudo systemctl status caddy'
